ClientInfoSystemMVC/Controllers/ClientsController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientInfoSystemMVC.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientService _clientService;

        public ClientsController(IClientService clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        public async Task<IActionResult> ClientList()
        {
            var clients = await _clientService.GetAllClients();
            
            return View(clients);
        }
        [HttpGet]
        public IActionResult UpdateClient(int id)
        {
            
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> UpdateClient(ClientRequestModel clientRequest)
        {
            if (!ModelState.IsValid) return View();
            await _clientService.UpdateClientById(clientRequest);
            return RedirectToAction("ClientList");
        }

        [HttpGet]
        public IActionResult AddClient()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddClient(ClientRequestModel clientRequest)
        {
            if (!ModelState.IsValid) return View();
            var client = await _clientService.AddClient(clientRequest);
            return RedirectToAction("ClientList");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteClient(int id)
        {
            await _clientService.DeleteClientById(id);
            return RedirectToAction("ClientList");
        }

        [HttpPost]
        public async Task<IActionResult> GetClientByEmail(string email)
        {
            var client = await _clientService.GetClientByEmail(email);
            return View(client);
        }

        [HttpGet]
        public async Task<IActionResult> GetClientById(int id)
        {
            var client = await _clientService.GetClientById(id);
            return View(client);
        }
    }
}

ClientInfoSystemMVC/Controllers/EmployeesController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ClientInfoSystemMVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeService _employeeService;

        public EmployeesController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        public async Task<IActionResult> EmployeeList()
        {
            var employees = await _employeeService.GetAllEmps();
            
            return View(employees);
        }

        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee(EmpInfoRequestModel requestModel)
        {
            await _employeeService.AddEmployee(requestModel);
            if (!ModelState.IsValid) return View();

            return RedirectToAction("EmployeeList");
        }

        [HttpGet]
        public IActionResult UpdateEmployee()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateEmployee(int Id, EmpInfoRequestModel requestModel)
        {
            await _employeeService.UpdateEmployee(Id, requestModel);
            if (!ModelState.IsValid) return View();

            return RedirectToAction("EmployeeList");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteEmployee(int id)
        {
            await _employeeService.DeleteEmployeeById(id);
            return RedirectToAction("EmployeeList");
        }

        [HttpGet]
        public async Task<ActionResult> GetEmployeeById(int id)
        {
            var employee = await _employeeService.GetEmployeeById(id);
            return View(employee);
        }

        [HttpGet]
        public ActionResult EmployeeLogin()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> EmployeeLogin(EmployeeLoginRequestModel model)
        {
            if (!ModelState.IsValid) return View();

            var employee = await _employeeService.Login(model.EmployeeID, model.Name, model.Password);
            if(employee == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid password");
                return View();
            }

            var claims = new List<Claim>
            {
                 new Claim(ClaimTypes.Name, employee.Name),
                 new Claim(ClaimTypes.NameIdentifier, employee.Id.ToString())
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

            return LocalRedirect("~/");
        }

        public async Task<ActionResult> EmployeeLogout()
        {
            await HttpContext.SignOutAsync();
            return LocalRedirect("~/");
        }
    }
}

ClientInfoSystemMVC/Controllers/InteractionsController.cs
using ApplicationCore.Exceptions;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientInfoSystemMVC.Controllers
{
    public class InteractionsController : Controller
    {
        private readonly IInteractionService _interactionService;

        public InteractionsController(IInteractionService interactionService)
        {
            _interactionService = interactionService;
        }

        public async Task<IActionResult> InteractionsList()
        {
            var interactions = await _interactionService.GetInteractions();
            
            return View(interactions);
        }
        [HttpGet]
        public IActionResult AddInteraction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddInteraction(InteractionRequestModel requestModel)
        {
            await _interactionService.AddInteraction(requestModel);
            return RedirectToAction("InteractionsList");
        }

        [HttpGet]
        public IActionResult UpdateInteraction()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateInteraction(int id, InteractionRequestModel requestModel)
        {
            await _interactionService.UpdateInteraction(id, requestModel);
            return RedirectToAction("InteractionsList");
        }
        [HttpGet]
        public async Task<IActionResult> DeleteInteraction(int id)
        {
            await _interactionService.DeleteInteraction(id);
            return RedirectToAction("InteractionsList");
        }

        [HttpGet]
        public async Task<IActionResult> InteractionWithClient(int id)
        {
            var interactions = await _interactionService.GetClientInteractionsById(id);
            if (!interactions.Any())
            {
                return View("_NotFound", "Shared");
            }
            return View(interactions);
        }

        [HttpGet]
        public async Task<IActionResult> InteractionWithEmployee(int id)
        {
            var interactions = await _interactionService.GetEmployeeInteractionsById(id);
            if (!interactions.Any())
            {
                return View("_NotFound", "Shared");
            }
            return View(interactions);
        }
    }
}

ClientInfoSystemMVC/Views/Interactions/AddInteraction.cshtml
@model ApplicationCore.Models.InteractionRequestModel
@{
    ViewData["Title"] = "Add Interaction";
}

<div class="container-fluid">
    <h1>Create Interaction</h1>
    <form asp-action="AddInteraction">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="ClientId">ClientId</label>
            <input type="text" class="form-control" asp-for="ClientId">

        </div>
        <div class="form-group">
            <label asp-for="EmpId">EmployeeId</label>
            <input type="text" class="form-control" asp-for="EmpId">

        </div>
        <div class="form-group">
            <label asp-for="IntType">Interaction Type (Ex: Telephone: T, Skype: S, InPerson : I, WebEx: W)</label>
            <input type="text" class="form-control" asp-for="IntType">

        </div>
        <div class="form-group">
            <label asp-for="IntDate">Interaction Date</label>
            <input type="date" class="form-control" asp-for="IntDate">

        </div>
        <div class="form-group">
            <label asp-for="Remarks">Remarks</label>
            <input type="text" class="form-control" asp-for="Remarks">

        </div>

        <button type="submit" class="btn btn-primary">Create</button>
        <a type="button" class="btn btn-success ml-2" asp-controller="Interactions" asp-action="InteractionsList">Back</a>
    </form>
</div>

ClientInfoSystemMVC/Views/Interactions/InteractionWithClient.cshtml
@model List<ApplicationCore.Models.InteractionResponseModel>
@{
}

<div class="container-fluid">
    <h1>Client Interactions Information</h1>
    <a type="button" class="btn btn-success mt-2 mb-2"  asp-controller="Clients" asp-action="ClientList">Back To Client List</a>
    <table class="table table-dark overflow-auto">
        <thead>
            <tr>
                <th scope="col">ClientName</th>
                <th scope="col">EmployeeName</th>
                <th scope="col">InteractionType</th>
                <th scope="col">InteractionDate</th>
                <th scope="col">Remarks</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var interaction in Model)
            {
                <tr>
                    <th scope="row">@interaction.ClientName</th>
                    <td>@interaction.EmployeeName</td>
                    <td>@interaction.IntType</td>
                    <td>@interaction.IntDate.Value.ToShortDateString()</td>
                    <td>@interaction.Remarks</td>
                    <td><a class="btn btn-primary" asp-controller="Interactions" asp-action="UpdateInteraction" asp-route-id="@interaction.Id">Modify</a></td>
                    <td><a class="btn btn-danger" asp-controller="Interactions" asp-action="DeleteInteraction" asp-route-id="@interaction.Id">Delete</a></td>
                </tr>

            }


        </tbody>
    </table>
</div>

ClientInfoSystemMVC/Views/Interactions/InteractionWithEmployee.cshtml
@model List<ApplicationCore.Models.InteractionResponseModel>
@{
}

<div class="container-fluid">
    <h1>Employee Interactions Information</h1>
    <a type="button" class="btn btn-success mt-2 mb-2"  asp-controller="Employees" asp-action="EmployeeList">Back To Employee List</a>
    <table class="table table-dark overflow-auto">
        <thead>
            <tr>
                <th scope="col">EmployeeName</th>
                <th scope="col">ClientName</th>
                <th scope="col">InteractionType</th>
                <th scope="col">InteractionDate</th>
                <th scope="col">Remarks</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var interaction in Model)
            {
                <tr>
                    <th scope="row">@interaction.EmployeeName</th>
                    <td>@interaction.ClientName</td>
                    <td>@interaction.IntType</td>
                    <td>@interaction.IntDate.Value.ToShortDateString()</td>
                    <td>@interaction.Remarks</td>
                    <td><a class="btn btn-primary" asp-controller="Interactions" asp-action="UpdateInteraction" asp-route-id="@interaction.Id">Modify</a></td>
                    <td><a class="btn btn-danger" asp-controller="Interactions" asp-action="DeleteInteraction" asp-route-id="@interaction.Id">Delete</a></td>
                </tr>

            }


        </tbody>
    </table>
</div>

ClientInfoSystemMVC/Views/Interactions/InteractionsList.cshtml
@model List<ApplicationCore.Models.InteractionResponseModel>
@{
    ViewData["Title"] = "Interactions Page";
}

<div class="container-fluid">
    <h1>Interactions Information</h1>
    <a class="btn btn-success mt-2 mb-2" asp-controller="Interactions" asp-action="AddInteraction">Create Interaction</a>
    <table class="table table-dark overflow-auto">
        <thead>
            <tr>
                <th scope="col">ClientName</th>
                <th scope="col">EmployeeName</th>
                <th scope="col">InteractionType</th>
                <th scope="col">InteractionDate</th>
                <th scope="col">Remarks</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var interaction in Model)
            {
                <tr>
                    <th scope="row"><a asp-controller="Clients" asp-action="GetClientById" asp-route-id="@interaction.ClientId">@interaction.ClientName</a></th>
                    <td><a asp-controller="Employees" asp-action="GetEmployeeById" asp-route-id="@interaction.EmpId">@interaction.EmployeeName</a></td>
                    <td>@interaction.IntType</td>
                    <td>@interaction.IntDate.Value.ToShortDateString()</td>
                    <td>@interaction.Remarks</td>
                    <td><a class="btn btn-primary" asp-controller="Interactions" asp-action="UpdateInteraction" asp-route-id="@interaction.Id">Modify</a></td>
                    <td><a class="btn btn-danger" asp-controller="Interactions" asp-action="DeleteInteraction" asp-route-id="@interaction.Id" onclick="return confirm('Are you sure to delete?')">Delete</a></td>
                </tr>

            }


        </tbody>
    </table>
</div>

ClientInfoSystemMVC/Views/Interactions/UpdateInteraction.cshtml
@model ApplicationCore.Models.InteractionRequestModel
@{
    ViewData["Title"] = "Update Interaction";
}


<div class="container-fluid">
    <h1>Update Interaction</h1>
    <form asp-action="UpdateInteraction">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="ClientId">ClientId</label>
            <input type="text" class="form-control" asp-for="ClientId">

        </div>
        <div class="form-group">
            <label asp-for="EmpId">EmployeeId</label>
            <input type="text" class="form-control" asp-for="EmpId">

        </div>
        <div class="form-group">
            <label asp-for="IntType">Interaction Type (Ex: Telephone: T, Skype: S, InPerson : I, WebEx: W)</label>
            <input type="text" class="form-control" asp-for="IntType">

        </div>
        <div class="form-group">
            <label asp-for="IntDate">Interaction Date</label>
            <input type="date" class="form-control" asp-for="IntDate">

        </div>
        <div class="form-group">
            <label asp-for="Remarks">Remarks</label>
            <input type="text" class="form-control" asp-for="Remarks">

        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <a type="button" class="btn btn-success ml-2" asp-controller="Interactions" asp-action="InteractionsList">Back</a>
    </form>
</div>